### ISSUE TITLE
Setup.sh failed after Line 84

### ISSUE THREAD

**Issue by MaFish18** [mainframe98/MediaWiki-Family-Installer#1]
Hi,

I was happy to find your Script, but for some reason is says:

"Installation is done. Starting MediaWiki installation now.
Couldn't open ~/mainpage.mediawiki"

I started the Script as root with "sh setrup.sh mainwiki/ REL1_31".

**Comment by mainframe98** [comment]
Yeah, that's one thing I should've addressed. I've ran into the same issue before, as it assumes the file to be present, and does not check if it actually exists. I also realize that the default value doesn't make much sense, so I'll address that too. In the meantime, defining `MAINPAGECONTENTPATH` in family.conf as `''` should resolve this particular issue.

**Comment by mainframe98** [comment]
This should be fixed with 92917de.
