### ISSUE TITLE
DB install - InvalidArgumentException - line 536 of /includes/libs/rdbms/database/Database.php

### ISSUE THREAD

**Issue by MaFish18** [mainframe98/MediaWiki-Family-Installer#2]
Hello,

while I tryed to install via the Script at the Point where it establish the (mariadb) database I am getting the following Error: 
[3ed9cfed7cb477cd1bffa0ac] [no req]   InvalidArgumentException from line 536 of /srv/www/htdocs/metawiki/includes/libs/rdbms/database/Database.php: Wikimedia\Rdbms\Database::getClass no viable database extension found for type 'mysql'. 
I am using REL1_31 from GitHub.

**Comment by mainframe98** [comment]
This seems not to be an error specific to my script. The error originates from the MediaWiki installer, and I suspected based on the error message that the PHP extension that handles the database connection does not exist. I'm afraid I can't be of much help here. You can try and report this error on [Phabricator](https://phabricator.wikimedia.org/) instead.
